apiVersion: v1
kind: PersistentVolume
metadata:
  name: va-va-gateway-log-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    path: /nfs-ocp/va/va-gateway-pv/log
    server: nfs.ocp.banksumselbabel.com

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: va-va-gateway-log-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  volumeName: va-va-gateway-log-pv
  storageClassName: ''

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: va-gateway
  name: va-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: va-gateway
  template:
    metadata:
      labels:
        app: va-gateway
    spec:
      containers:
        - image: docker.io/visiondgmlpt/va-gateway:prod-bsb
          imagePullPolicy: IfNotPresent
          name: va-gateway
          ports:
            - containerPort: 8080
          resources: {}
          volumeMounts:
            - mountPath: /log/
              name: va-va-gateway-log-pvc
      volumes:
        - name: va-va-gateway-log-pvc
          persistentVolumeClaim:
            claimName: va-va-gateway-log-pvc
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: va-gateway
  labels:
    app: va-gateway
spec:
  type: ClusterIP
  selector:
    app: va-gateway
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
